# -*- coding: utf-8 -*-
"""Distinct Numbers MCW Nish.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luMdqW0EkXMiC4Mv8mfsTewz0atHx95s
"""

# Distinct Numbers - Nish

n = int(input())
arr = list(map(int,input().split()))
print(len(list(set(arr))))