# -*- coding: utf-8 -*-
"""increasing array mcw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18m4A57jE6BQk7PLdPHcwc7pmiw04aUHh
"""

# increasing array - nish

def countTurns(n,arr):
  turn = 0
  for i in range(1,n):
    if arr[i]<arr[i-1]:
      turn+=abs(arr[i]-arr[i-1])
      arr[i] = arr[i-1]
  print(turn)

n = int(input())
arr = list(map(int,input().split()))
countTurns(n,arr)