# -*- coding: utf-8 -*-
"""missing number mcw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YnR4pJVv9To5nQoIXoXDcSd0b8V_cY2
"""

# missing number - nish

def findMissingNumber(n,arr):
  sumWithout = sum(arr)
  sumWith = (n*(n+1))/2
  res = sumWith - sumWithout
  print(int(res))

n = int(input())
arr = list(map(int,input().split()))
findMissingNumber(n,arr)