# -*- coding: utf-8 -*-
"""permutations mcw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14sPekj7beRnKD6sAH9gkGkru3MSVSEQa
"""

# permutations - nish

def findBeautifulPerm(n):
  if n==3 or n==2:
    print('NO SOLUTION')
    return
  arr = []
  for i in range(1,n+1):
    if i%2==0:
      print(i,end=" ")
    else:
      arr.append(i)
  print(*arr)


n = int(input())
findBeautifulPerm(n)