# -*- coding: utf-8 -*-
"""repetitions mcw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hc0IC_xI6mCjrdya-QB9VrKuK6wc0rWH
"""

# repetitions - nish

def findLongestRepetition(string):
  longestTillNow = 0
  currStrLen = 0

  if len(string)>0:
    longestTillNow = 1
    currStrLen = 1

  for i in range(1,len(string)):
    if string[i]==string[i-1]:
      currStrLen += 1
    else:
      if currStrLen > longestTillNow:
        longestTillNow = currStrLen
      currStrLen = 1
      
  if currStrLen > longestTillNow:
        longestTillNow = currStrLen
  print(longestTillNow)


string = input()
findLongestRepetition(string)