# -*- coding: utf-8 -*-
"""trailing 0s mcw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19u2DBim5KyJHHPSqNSLcV9wQqUoV9Z23
"""

# trailing 0s - nish
import math
n = int(input())
count = 0
i=5
while(n/i>=1):
  count+=math.floor(n/i)
  i*=5
print(int(count))