# -*- coding: utf-8 -*-
"""weird algorithm mcw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OyxBQ0PUChrO_Zw0qNFhEPJ4LpmQ34Rd
"""

# weird alg nish

n = int(input())
while n!=1:
  print(int(n),end=" ")
  if n%2==0:
    n = n/2
  else:
    n = (n*3)+1
print(int(n))